name: Generate and provide the Hugo cache directory for a Windows environment

on:
  workflow_dispatch:

jobs:
  read-tool-versions:
    uses: ./.github/workflows/read-tool-versions.yml

  build-and-upload:
    runs-on: windows-latest
    needs: [read-tool-versions]
    steps:
      - name: Checkout
        uses: actions/checkout@5
        with:
          submodules: recursive

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          cache: false # to avoid Warning: "Restore cache failed: Dependencies file is not found in /home/runner/work/handbook/handbook. Supported file pattern: go.sum"
          go-version: ${{ needs.read-tool-versions.outputs.go_version }}

      - name: Install Dart Sass
        run: choco install sass --version ${{ needs.read-tool-versions.outputs.dart_sass_version }}

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ needs.read-tool-versions.outputs.nodejs_version }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        env:
          BASE_URL: ${{ env.DEPLOYED_BASE_URL }}
        run: npm run build

      - name: Find Hugo cache directory
        id: find-cache
        shell: pwsh
        run: |
          $cachePath = Join-Path $env:LOCALAPPDATA 'hugo_cache'
          echo "HUGO_CACHE_DIR=$cachePath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Install 7zip
        run: choco install 7zip.install -y

      - name: Compress Hugo cache directory
        run: 7z a -tzip hugo_cache.zip ${{ env.HUGO_CACHE_DIR }}

      - name: Upload hugo_cache.zip
        uses: actions/upload-artifact@v4
        with:
          name: hugo-cache
          path: hugo_cache.zip
